server:
  port: 8082
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
    password: manager
  jpa:
    show-sql: true
    format-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  thymeleaf:
    mode: HTML
    cache: false
    encoding: UTF-8